attributes:
  encounter_id:
    field: RecordId
    type: RecordId
  birth_year:
    field: BirthYear
    type: LastName
  age_at_encounter:
    field: AgeAtEncounter
    type: PostalCode
  encounter_date:
    field: EncounterDate
    type: BirthDate
  encounter_type:
    field: EncounterType
    type: FirstName
  patient_gender:
    field: Gender
    type: Sex
  ssn:
    field: PatientSSN
    type: SocialSecurityNumber

token_rules:
  T_ALL_BASE:
    - field: RecordId
      expression: "T|U"
    - field: BirthYear
      expression: "T|U"
    - field: EncounterType
      expression: "T|U"
    - field: EncounterDate
      expression: "T|D"
    - field: Gender
      expression: "T|S(0,1)|U"
    - field: AgeAtEncounter
      expression: "T|S(0,5)|U"
    - field: PatientSSN
      expression: "T|M(\\d+)"
  T_INITIALS_PLUS_AGE:
    - field: BirthYear
      expression: "T|S(0,2)|U"
    - field: EncounterType
      expression: "T|S(0,2)|U"
    - field: EncounterDate
      expression: "T|Y"
    - field: AgeAtEncounter
      expression: "T|S(0,4)|U"
  T_IDENTITY_LIGHT:
    - field: RecordId
      expression: "T|S(0,8)|U"
    - field: EncounterDate
      expression: "T|Y"
    - field: Gender
      expression: "T|U"
