column_mappings:
  RecordId:
    column_name: "RecordId"
    type: RecordId
  BirthDate:
    column_name: "BirthDate"
    type: BirthDate
  FirstName:
    column_name: "FirstName"
    type: FirstName
  LastName:
    column_name: "LastName"
    type: LastName
  PostalCode:
    column_name: "PostalCode"
    type: PostalCode
  Sex:
    column_name: "Sex"
    type: Sex
  SocialSecurityNumber:
    column_name: "SocialSecurityNumber"
    type: SocialSecurityNumber

token_rules:
  T1:
    - field: LastName
      expression: "T|U"
    - field: FirstName
      expression: "T|S(0,1)|U"
    - field: Sex
      expression: "T|U"
    - field: BirthDate
      expression: "T|D"
  T2:
    - field: LastName
      expression: "T|U"
    - field: FirstName
      expression: "T|U"
    - field: BirthDate
      expression: "T|D"
    - field: PostalCode
      expression: "T|S(0,3)|U"
  T3:
    - field: LastName
      expression: "T|U"
    - field: FirstName
      expression: "T|U"
    - field: Sex
      expression: "T|U"
    - field: BirthDate
      expression: "T|D"
  T4:
    - field: SocialSecurityNumber
      expression: "T|M(\\d+)"
    - field: Sex
      expression: "T|U"
    - field: BirthDate
      expression: "T|D"
  T5:
    - field: LastName
      expression: "T|U"
    - field: FirstName
      expression: "T|S(0,3)|U"
    - field: Sex
      expression: "T|U"
