[project]
name = "openlinktoken-core-ai"
version = "2.0.0"
requires-python = ">=3.10"
dynamic = [
  "authors",
  "dependencies",
  "description",
  "optional-dependencies",
  "readme",
  "urls",
]

[project.entry-points."openlinktoken.inference_providers"]
ml1 = "openlinktoken_core_ai.ml1_signature_provider:OnnxML1SignatureProvider"

[project.entry-points."openlinktoken.tokens.definitions"]
ml1_token = "openlinktoken_core_ai.tokens.ml1_token:ML1Token"

[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src/main"]

[tool.pytest.ini_options]
pythonpath = ["src/main", "src/test", "../../openlinktoken/src/main"]
testpaths = ["src/test"]
